main: com.cavetale.skyblock.SkyblockPlugin
name: Skyblock

version: ${version}
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/Skyblock
description: Skyblock Plugin

depend: [Core, Mytems, Creative]
softdepend: []

commands:

  skyblock:
    aliases: []
    description: Skyblock Command
    permission: skyblock.skyblock
    usage: |-
      /skyblock

permissions:

  skyblock.skyblock:
    description: Use /skyblock
    default: op
