main: com.cavetale.skyblock.SkyblockPlugin
name: Skyblock

version: ${version}
api-version: '1.21'

author: StarTux
website: https://github.com/StarTux/Skyblock
description: Skyblock Plugin

depend:
- Core
- Mytems
- Creative
- Inventory

softdepend: []

commands:

  skyblock:
    aliases: []
    description: Skyblock Command
    permission: skyblock.skyblock
    usage: |-
      /skyblock

  skyblockadmin:
    aliases: [skyblockadm]
    description: Skyblock Admin Command
    permission: skyblock.admin
    usage: |-
      /skyblockadmin

permissions:

  skyblock.skyblock:
    description: Use /skyblock
    default: op

  skyblock.admin:
    description: Use /skyblockadmin
    default: op

  skyblock.import:
    description: Import worlds from creative
    default: op